MODEL:
  TYPE: CLIP
  NAME: "V_VIT-B-32_L_Large"
  EMBED_DIM: 768
  IMAGE_RESOLUTION: 224
  VISION_LAYERS: 12
  VISION_WIDTH: 768
  VISION_PATCH_SIZE: 32
  CONTEXT_LENGTH: 77
  VOCAB_SIZE: 49408
  TRANSFORMER_WIDTH: 768
  TRANSFORMER_HEADS: 12
  TRANSFORMER_LAYERS: 12